### ISSUE TITLE
web-console gem conflict

### ISSUE THREAD

**Issue by tirith** [discourse/logster#24]
After installing the logster gem, I was getting the following error:
```
$ rake middleware --trace
** Invoke middleware (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
No such middleware to insert before: ActionDispatch::DebugExceptions
/home/tirith/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/stack.rb:125:in `assert_index'
/home/tirith/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/stack.rb:88:in `insert'
...
```

The conflict ended up being with the web-console gem, rails app booted up fine w/ logster after removing it from the Gemfile. I don't really use web-console anyway, but figured in-case someone had it in their Gemfile and ran into the middleware issue, they would see this.

Thanks for this handy tool.

**Comment by SamSaffron** [comment]
Interesting, I do want to get this fixed

**Comment by jiajiawang** [comment]
Had the same problem when using logster together with better_errors.

The reason is that logster will replace ActionDispatch::DebugExceptions with Logster::Middleware::DebugExceptions. And gems like 'better_errors' will try to insert their middlewares after ActionDispatch::DebugExceptions.

To avoid this error, make sure logster is added behind those gems in Gemfile.

Probably it's a good idea to add this notice to the README file.

**Comment by SamSaffron** [comment]
Ahh ... I see, can you add a note to the README ?

**Comment by jiajiawang** [comment]
Sure
