### ISSUE TITLE
Heroku deployment

### ISSUE THREAD

**Issue by n-rodriguez** [discourse/logster#35]
Hi! 

How do you specify Redis params for an Heroku style deployment? (Redis is living in a container and the Rails app in an other one)

Thank you!

**Comment by SamSaffron** [comment]
Should be pretty straight forward to configure that, you just need to point
it at the right redis.

**Comment by lumenlunae** [comment]
Don't know if you want to add this to the readme (I'd be more than happy to, but obviously your call, it might be just as useful here)-- I had issues with Heroku deployment and thought it was Redis related because nothing showed up in my logs on production though everything worked on development.

Turns out I forgot I was using the ralis_12factor gem which uses its own Logger for Rails, and wasn't coopering with Logster. In config/initializers.rb I added this to get it working: 

Rails.env.production? 
 Rails.logger.extend(ActiveSupport::Logger.broadcast(Logster.logger))
end

**Comment by SamSaffron** [comment]
Sure, anything to improve the readme is welcome!

**Comment by lumenlunae** [comment]
Great--PR created!

**Comment by tgxworld** [comment]
Close in https://github.com/discourse/logster/pull/36.
